# You can set player's start balance and change plugin messages #

Settings:
  Prefix: "&e(&6CraftCoins&e)"
  Balance:
    coins-name: "coins"
    create-on-player-join: true
    start-balance: 50
  Enable-Commands: true

# Messages #
MESSAGES:
  COMMANDS:
    DISABLED: "&cThis command disabled by server administrator"
    COINS-BALANCE-PLAYER: "&8<player> have &6<coins> #coins"
    COINS-BALANCE: "&8You have &6<coins> #coins"
    NOT-ONLINE: "&cPlayer &4<player> &cisn't online!"
    BALANCE-IS-FROZEN: "&cYour balance is fozen! You can't buy or sell anything!"
    LOW-BALANCE: "&cYou have no #coins on balance!"
    COINS-SET:
      SUCCESSFUL: "&8Player &6<player> &8now have &6<coins> #coins"
      USE: "&6Use: &8/coins set &6<player> <ammount>"
    COINS-PAY:
      ERROR: "&8You don't have &6<coins> #coins &8on balance!"
      SUCCESSFUL: "&8Player &6<player> &8now have &6<coins> #coins"
      TARGET: "&8Player &6<player> &8send to you &6<coins> #coins"
      USE: "&6Use: &8/coins pay &6<receiver> <ammount>"
    COINS-ADD:
      SUCCESSFUL: "&8Player &6<player> &8now have &6<coins> #coins"
      USE: "&6Use: &8/coins add &6<player> <ammount>"
    COINS-TAKE:
      SUCCESSFUL: "&8Player &6<player> &8now have &6<coins> #coins"
      USE: "&6Use: &8/coins add &6<player> <ammount>"