# You can set player's start balance and change plugin messages #

Settings:
  Prefix: "&5(&dCraftWallet&5)"
  Balance:
    money-symbol: "$"
    create-on-player-join: true
    start-balance: 50
  Enable-Commands: true

# Messages #
MESSAGES:
  COMMANDS:
    DISABLED: "&cThis command disabled by server administrator"
    WALLET-BALANCE-PLAYER: "&7<player> have &d<count>#walletSymbol"
    WALLET-BALANCE: "&7You have &d<count>#walletSymbol"
    NOT-ONLINE: "&cPlayer &4<player> &cisn't online!"
    BALANCE-IS-FROZEN: "&cYour balance is fozen! You can't buy or sell anything!"
    LOW-BALANCE: "&cYou have no#walletSymbol on balance!"
    WALLET-SET:
      SUCCESSFUL: "&7Player &d<player> &7now have &d<count>#walletSymbol"
      USE: "&dUse: &7/coins set &d<player> <ammount>"
    WALLET-PAY:
      YOUSELF: "&cYou can't send money to youself!"
      ERROR: "&7You don't have &d<count>#walletSymbol &7on balance!"
      SUCCESSFUL: "&7Player &d<player> &7now have &d<count>#walletSymbol"
      TARGET: "&7Player &d<player> &7send to you &d<count>#walletSymbol"
      USE: "&dUse: &7/coins pay &d<target> <ammount>"
    WALLET-ADD:
      SUCCESSFUL: "&7Player &d<player> &7now have &d<count>#walletSymbol"
      USE: "&dUse: &7/coins add &d<player> <ammount>"
    WALLET-TAKE:
      SUCCESSFUL: "&7Player &d<player> &7now have &d<count>#walletSymbol"
      USE: "&dUse: &7/coins add &d<player> <ammount>"