name: CraftWallet
main: ru.undefined1.CraftCoins.CraftWallet
version: "1.1"
author: undefined1
api: ["1.0.0"]

commands:
  money:
    usage: "/money"
    permission: CraftWallet.cmd

permissions:
  CraftWallet.reload:
    default: op
  CraftWallet.view:
    default: true
  CraftWallet.pay:
    default: true
  CraftWallet.take:
    default: op
  CraftWallet.add:
    default: op
  CraftWallet.set:
    default: op
  CraftWallet.cmd:
    default: true